language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

  services:
    - mysql

before_script:
  - cp .env.travis .env
  - mysql -e 'create database testing;'
  - composer self-update
  - php artisan key:generate
  - php artisan migrate --seed

script:
  - vendor/bin/phpunit